---
title: "Dec 22 Meeting Notes"
# author: "Quang-Vinh Do 8771581"
date: "22/12/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## SEIR Compartment Model

- Higher focus on removed loss compared to infected cases as it is on different scales and the infected cases has higher noise

- Step 1
  - Time varying parameters $\alpha_1, \alpha_2 ..$ for time periods under different policies. In this case $\alpha_i$ are independent of each other and they each cover wide time periods.
- Step 2
  - Time varying parameter as a function $\alpha_t = f(\phi_t)$. In this case $\alpha_t$ is assumed to be dependent and related by some parameter $\phi_t$.

- Extra compartments such as unobserved infected cases could lead to problems related identifiability with the interaction between the Exposed and Unobserved Infected compartments.

- Notice that currently this model produces predictions and forecasts $\hat{Y_1}, \hat{Y_2}, ... , \hat{Y_{t+h}}$ given only the estimated parameters. Instead to make it more presentable we will use $Y_{t-1}$ as the initial values to get $\hat{Y_t}$ with IVP solver (one step prediction) and use latest known $Y_t$ to get $h$ step future forecasts $\hat{Y_{t+1}}, ... , \hat{Y_{t+h}}$



## Poisson Regression

- Notice relationship between poisson model definition and the ODEs for the SEIR model. Look into more detail if we can relate them somehow.

- This model produces predictions $\hat{Y_t}$ using previous known $Y_{t-1}$ in contrast to SEIR model which simply produces the entire observed values of $\hat{Y}$ at once.

- Add time varying parameters $\beta_t$ 

- Cross validation rmse could be calculated differently. Get estimates instead for 1-step forecast error, 5-step forecast error, etc. instead of averaging all forecast errors as the 1-step errors will be much lower compared to the 3 week forecast.